renovate:
  enabled: true
  cronjob:
    # At 01:00 every day
    schedule: '0 1 * * *'

  renovate:
    # See https://docs.renovatebot.com/self-hosted-configuration
    config: |
      {
        "platform": "github",
        "repositories": [
          "elserhumano/renovate-gitops"
        ]
      }

  existingSecret: "renovate-secrets"
